-- Spring Modulith Event Publication Registry Table for H2 Database
-- This table is used by Spring Modulith's transactional outbox pattern

CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION (
    ID VARCHAR(36) NOT NULL,
    COMPLETION_DATE TIMESTAMP,
    EVENT_TYPE VARCHAR(255) NOT NULL,
    LISTENER_ID VARCHAR(255),
    PUBLICATION_DATE TIMESTAMP NOT NULL,
    SERIALIZED_EVENT CLOB NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    COMPLETION_ATTEMPTS INT NOT NULL,
    LAST_RESUBMISSION_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);
